language: java
sudo: false

addons:
  chrome: stable

before_install:
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - hiptest-publisher -c junit-selenium.conf --token=$SECRET_TOKEN --only=tests --test-run-id=101683

install:
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

script:
  - whereis google-chrome-stable
  - mvn package

after_script:
  - hiptest-publisher -c junit-selenium.conf --token=$SECRET_TOKEN -p "target/surefire-reports/TEST-com.coffeemachine.*.xml" --test-run-id=101683
